---
- name: Create app dir
  become: yes
  file:
    path: /var/www
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0777

- name: Create env file
  become: yes
  file:
    path: /etc/profile.d/vars.sh
    state: touch
    owner: ec2-user
    group: ec2-user
    mode: 0777

- name: Create shared app dir
  become: yes
  file:
    path: /var/www/{{ application_name }}/shared/config/
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0777

- name: Create database.yml
  template:
    src: roles/common/templates/database.yml.j2
    dest: /var/www/qiita_clone_2019/shared/config/database.yml

- name: Create master.key
  template:
    src: roles/common/templates/master.key.j2
    dest: /var/www/qiita_clone_2019/shared/config/master.key
